import BreadcrumbItem from "antd/es/breadcrumb/BreadcrumbItem";
import Breadcrumb from "antd/es/breadcrumb/Breadcrumb";
import Layout from "antd/es/layout/layout";
import Menu from "antd/es/menu/menu";
import { Footer, Header, Content } from "antd/es/layout/layout";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { redirect } from "next/navigation";
import { SearchOutlined } from "@ant-design/icons";
import { HeartFilled } from "@ant-design/icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [{ id: 1, name: "বইয়ের লিস্ট ", href: "/bookList" }];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items = navItems.map((item, index) => ({
    key: item.id,
    label: <Link href={item.href}>{item.name}</Link>,
  }));

  // Function to generate breadcrumb items from the current path
  const generateBreadcrumbItems = () => {
    const pathnames = redirect.pathname.split("/").filter((x) => x);
    const breadcrumbItems = pathnames.map((path, index) => {
      // Generate the URL for each breadcrumb item
      const href = "/" + pathnames.slice(0, index + 1).join("/");
      return (
        <BreadcrumbItem key={href}>
          <Link href={href}>{path}</Link>
        </BreadcrumbItem>
      );
    });
    return breadcrumbItems;
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <Header
            style={{
              position: "sticky",
              top: 0,
              zIndex: 1,
              width: "100%",
              display: "flex",
              alignItems: "center",
            }}
          >
            <div className="demo-logo" />
            <Menu
              theme="dark"
              mode="horizontal"
              defaultSelectedKeys={["2"]}
              items={items}
              style={{ flex: 1, minWidth: 0 }}
            />
          </Header>
          <Content style={{ padding: "0 48px" }}>
            {/* <Breadcrumb items={breadcrumbItems} style={{ margin: "16px 0" }} /> */}
            {generateBreadcrumbItems()}
            <div
              style={{
                padding: 24,
                minHeight: 380,
                background: "white",
                borderRadius: "20px",
              }}
            >
              {children}
            </div>
          </Content>
          <Footer style={{ textAlign: "center" }}>
            <SearchOutlined /> Tigo Finder ©{new Date().getFullYear()} Created
            by Al Amin with{" "}
            <span>
              {" "}
              <HeartFilled twoToneColor />
            </span>
          </Footer>
        </Layout>
      </body>
    </html>
  );
}
